### ISSUE TITLE
Make Single Item View Homepage

### ISSUE THREAD

**Issue by cspark-development** [HL-Inventory-App-Project/Inventory-App#13]
Make the Single Item View Homepage

It should have

- Logo
- Item Name
- Item Image
- Item Description
- Delete Item Button
- Update Item Button

**Comment by laraibxsunny** [comment]
-Item Name
-Item Image
-Item Description
Done

**Comment by laraibxsunny** [comment]
-Delete Item Button
-Update Item Button
Issue Completed
