### ISSUE TITLE
Serverside validation - Backend

### ISSUE THREAD

**Issue by cspark-development** [HL-Inventory-App-Project/Inventory-App#18]
Use validation to ensure any PUT requests etc have validation and will throw an error if not all the correct info is provided

**Comment by Muhyidin-Abdi** [comment]
updated the PUT method to Validate user input brfore sending. Tested with postman - works fine

**Comment by cspark-development** [comment]
Cannot see the commit, please ensure you have committed.

**Comment by cspark-development** [comment]
Solved in https://github.com/HL-Inventory-App-Project/Inventory-App/commit/33ca5587a653e60c88d0fd211a06091d600599ab
